[versions]
activity = "1.10.1"
agp = "8.13.2"
androidsvgdrawableGradlePlugin = "3.1.1"
annotation = "1.9.1"
coordinatorlayout = "1.3.0"
core = "1.16.0"
coreSplashscreen = "1.0.1"
drawerlayout = "1.2.0"
guava = "33.5.0-android"
json = "4.0.28"
jsr305 = "3.0.2"
junit = "4.13.2"
swipelayout = "1.2.0"
logbackAndroid = "3.0.0"
loggingInterceptor = "5.2.1"
msgpackCore = "0.9.10"
okhttp = "5.2.1"
osmdroidAndroid = "6.1.20"
maplibreGl = "11.11.0"
recyclerview = "1.4.0"
slf4jApi = "2.0.17"
supportV13 = "28.0.0"
preferenceV7 = "28.0.0"
preferenceV14 = "28.0.0"
preferencex = "1.2.1"

[libraries]
activity = { module = "androidx.activity:activity", version.ref = "activity" }
androidsvgdrawable-gradle-plugin = { module = "fr.avianey.androidsvgdrawable:gradle-plugin", version.ref = "androidsvgdrawableGradlePlugin" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
coordinatorlayout = { module = "androidx.coordinatorlayout:coordinatorlayout", version.ref = "coordinatorlayout" }
core = { module = "androidx.core:core", version.ref = "core" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
drawerlayout = { module = "androidx.drawerlayout:drawerlayout", version.ref = "drawerlayout" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
json = { module = 'org.apache.groovy:groovy-json', version.ref = "json" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
swipelayout = { module = "com.daimajia.swipelayout:library", version.ref = "swipelayout" }
logback-android = { module = "com.github.tony19:logback-android", version.ref = "logbackAndroid" }
msgpack-core = { module = "org.msgpack:msgpack-core", version.ref = "msgpackCore" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
osmdroid-android = { module = "org.osmdroid:osmdroid-android", version.ref = "osmdroidAndroid" }
maplibre-gl = { module = 'org.maplibre.gl:android-sdk', version.ref = "maplibreGl" }
preferencex = { group = "androidx.preference", name = "preference", version.ref = "preferencex" }
preference-v7 = { module = "com.android.support:preference-v7", version.ref = "preferenceV7" }
preference-v14 = { module = "com.android.support:preference-v14", version.ref = "preferenceV14" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4jApi" }
support-v13 = { module = "com.android.support:support-v13", version.ref = "supportV13" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

